### ISSUE TITLE
Investigate ParameterSet being held by pointer in L1Trigger

### ISSUE THREAD

**Issue by makortel** [makortel/framework#648]
Inspect the files

- [x] `L1Trigger/CSCTrackFinder/test/analysis/CSCTFEfficiency.h`
- [x] `L1Trigger/DTTrackFinder/interface/L1MuDTTFConfig.h`
- [x] `L1Trigger/GlobalMuonTrigger/src/L1MuGMTConfig.h`
- [x] `L1Trigger/TrackFindingTracklet/plugins/ProducerChannelAssignment.cc`
- [x] `L1Trigger/TrackTrigger/interface/Setup.h`
- [x] `L1Trigger/TrackerTFP/plugins/ProducerDemonstrator.cc`
- [x] `L1TriggerConfig/DTTPGConfig/interface/DTConfigBti.h`
- [x] `L1TriggerConfig/DTTPGConfig/interface/DTConfigTraco.h`
- [x] `L1TriggerConfig/GMTConfigProducers/interface/L1MuGMTParametersProducer.h`

and either migrate to something else, or explain here why the pattern is safe

**Comment by wddgit** [comment]
CSCTFEfficiency. Pointer is only used in beginJob so it should be OK. I'll modify the module to set the pointer to null at the end of beginJob. Note this module isn't currently compiled (commented out in BuildFile) and fails compilation for several other reasons if you try to compile it.

L1MuDTTFConfig.h. The pointer to ParameterSet data member can be deleted by simply passing the ParameterSet reference as an argument to the one function it.

L1MuGMTConfig.h No need for the ParameterSet* data member. One can simply use the constructor argument. It is only needed in the constructor. Delete the data member.

ProducerChannelAssignment.cc The easiest fix is to make the data member a ParameterSet instead of a pointer and do a deep copy to it.

Setup.h These pointers will always point at ParameterSets in the registry, not in ProcessDesc. Therefore there is not a problem and nothing needs to be done.

ProducerDemonstrator.cc The easiest fix is to make the data member a ParameterSet instead of a pointer and do a deep copy to it.

DTConfigTraco.h and DTConfigBti.h The pointers are already commented out. I deleted the comments.

L1MuGMTParametersProducer.h Already makes a copy on the heap. Does not need to be modified.

Matti, Chris and I discussed L1MuGMTConfig.h and L1MuDTTFConfig.h on Tuesday after the Core meeting in person and at that time discussed further  changes in those classes (related to static variables and some unusual ways of initializing them). But after looking more closely, I became convinced the existing code was not as bad as we thought although I still don't like it. There are also more complications than we discussed to those changes and they are not directly related to the ParameterSet pointer issue, I think we should do it in a separate PR if we still think those improvements are worth pursuing..

PR cms-sw/cmssw#42654 will resolve all of these when merged.
